apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: antigravity-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/antigravity-k8s-lab.git
    targetRevision: HEAD
    path: k8s/01-app-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-lab-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
