apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-primary-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-primary"
  claimRef:
    namespace: k8s-lab-app
    name: data-postgres-postgresql-primary-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-read-pv
  labels:
    type: local
spec:
  storageClassName: "manual"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-read"
  claimRef:
    namespace: k8s-lab-app
    name: data-postgres-postgresql-read-0
