apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-primary-pv
  labels:
    type: local
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-primary"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-read-pv
  labels:
    type: local
spec:
  storageClassName: "local-path"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-read"
